# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gsis_id', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=3)),
                ('total_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passing_yards', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('passing_tds', models.IntegerField()),
                ('rushing_tds', models.IntegerField()),
                ('receiving_tds', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('week', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='football_app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='TWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('W', models.BooleanField()),
                ('QB_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('RB1_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('RB2_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('WR1_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('WR2_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('WR3_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TE_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('record', models.CharField(max_length=30)),
                ('week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=69)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=69)),
                ('W', models.IntegerField()),
                ('L', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tweek',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='football_app.User'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football_app.User'),
        ),
    ]
