# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passing_yards', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('passing_tds', models.IntegerField()),
                ('rushing_tds', models.IntegerField()),
                ('receiving_tds', models.IntegerField()),
                ('receptions', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='total_points',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='pweek',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='football_app.Player'),
        ),
    ]
