# Generated by Django 2.2.6 on 2019-10-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0002_auto_20191022_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='passing_tds',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passing_yards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='receiving_tds',
        ),
        migrations.RemoveField(
            model_name='player',
            name='receiving_yards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='receptions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rushing_tds',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rushing_yards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_points',
        ),
    ]
