# Generated by Django 2.2.6 on 2019-10-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0003_auto_20191023_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='passing_tds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='passing_yards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='receiving_tds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='receiving_yards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='receptions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='rushing_tds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='rushing_yards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweek',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passing_yards', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('passing_tds', models.IntegerField()),
                ('rushing_tds', models.IntegerField()),
                ('receiving_tds', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('player', models.ForeignKey(on_delete='CASCADE', related_name='weeks', to='football_app.Player')),
            ],
        ),
    ]
